### ISSUE TITLE
createToken makes a duplicate query

### ISSUE THREAD

**Issue by sajad2176** [laravel/passport#1313] opened 2020-07-06 07:57 UTC
- Passport Version: 9.3
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:

createToken() method  makes a duplicate query

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/42096679/86569456-afd7d500-bf83-11ea-837a-d1620c758317.png)

**Comment by driesvints** [comment] 2020-07-06 09:31
Probably a duplicate of https://github.com/laravel/passport/issues/382

**Closed by driesvints** 2020-07-06 09:31 UTC
