### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by monoland** [laravel/passport#774] opened 2018-07-21 06:59 UTC
```
Problem 1
    - Conclusion: don't install laravel/passport v6.0.6
    - Conclusion: don't install laravel/passport v6.0.5
    - Conclusion: don't install laravel/passport v6.0.4
    - Conclusion: don't install laravel/passport v6.0.3
    - Conclusion: don't install laravel/passport v6.0.2
    - Conclusion: don't install laravel/passport v6.0.1
    - Conclusion: don't install laravel/passport v6.0.0
    - Conclusion: don't install laravel/passport 6.0.x-dev
    - Conclusion: remove paragonie/random_compat v9.99.99
    - Installation request for laravel/passport ^6.0 -> satisfiable by laravel/passport[6.0.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.0.5, v6.0.6].
    - Conclusion: don't install paragonie/random_compat v9.99.99
    - laravel/passport 6.0.x-dev requires league/oauth2-server ^7.0 -> satisfiable by league/oauth2-server[7.0.0, 7.1.0, 7.1.1, 7.2.0].
    - league/oauth2-server 7.1.0 requires defuse/php-encryption ^2.1 -> satisfiable by defuse/php-encryption[v2.1.0, v2.2.0].
    - league/oauth2-server 7.1.1 requires defuse/php-encryption ^2.1 -> satisfiable by defuse/php-encryption[v2.1.0, v2.2.0].
    - league/oauth2-server 7.2.0 requires defuse/php-encryption ^2.1 -> satisfiable by defuse/php-encryption[v2.1.0, v2.2.0].
    - league/oauth2-server 7.0.0 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - defuse/php-encryption v2.1.0 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - defuse/php-encryption v2.2.0 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].
```

my php version
```
PHP 7.2.6 (cli) (built: May 25 2018 06:18:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.6, Copyright (c) 1999-2018, by Zend Technologies
```

my composer.json
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by lifecrawler** [comment] 2018-07-21 11:43
same problem here

**Comment by trs-king** [comment] 2018-07-21 12:18
Same problem! I'm using Laravel 5.6 with PHP 7.1.13.

**Comment by gabeta** [comment] 2018-07-21 15:30
I have same Problem

**Comment by marceloamp2** [comment] 2018-07-21 17:41
I have same Problem

**Comment by scotthelps** [comment] 2018-07-21 20:11
Yeah, same issue here.

**Comment by solofeed** [comment] 2018-07-21 20:57
The same problem with fresh install laravel application.
Laravel version: 5.6.28
PHP 7.2.7

**Comment by maranesi** [comment] 2018-07-21 22:56
The problem is this:
```
paragonie / random_compat v9.99.99
```
* https://github.com/paragonie/random_compat/tree/v9.99.99

Version v2.0.17 does not have this problem.
I solved it temporarily by adding the following line to composer.json:
```
"paragonie / random_compat": "2. *"
```

Now it's working.

**Comment by Donovan-H** [comment] 2018-07-21 23:30
It seems like an intentional change by the random_compat guy! 

See: https://github.com/paragonie/random_compat/issues/147

Passport requires `league/oauth2-server` which requires `defuse/php-encryption` hence the issues.

The maintainer has made a pull request for the php-encryption package [here](https://github.com/defuse/php-encryption/pull/408#issue-193087966), with a brief explanation. 

Hopefully it will be merged soon 🤞.

**Comment by nasrulhazim** [comment] 2018-07-21 23:39
I did the following to fix the installation at the moment.

```
composer require paragonie/random_compat:2.*
composer require laravel/passport
```

**Comment by warlord0** [comment] 2018-07-23 07:30
Same issue with Laravel 5.5.40 Similar resolution as above:

```
composer require paragonie/random_compat=~2.0
composer require laravel/passport=~4.0
```

**Comment by Fh-abeyer** [comment] 2018-07-23 20:09
Just more information on nasrulhazim's solution it worked for me but I could not install through homestead I had to use my global composer  in the folder to download the packages.

**Comment by amit-teqmavens** [comment] 2018-07-24 05:44
Thanks @nasrulhazim .. Your solution worked for me :)

**Comment by amitmeetu12** [comment] 2018-07-24 05:45
Thanks @nasrulhazim .. Your solution worked for me :)

**Comment by gabeta** [comment] 2018-07-24 22:06
@nasrulhazim it work for me thanks

**Comment by Sephster** [comment] 2018-07-25 10:01
[Version 2.2.1](https://github.com/defuse/php-encryption/releases/tag/v2.2.1) of php-encryption has been released. There shouldn't be a need for a workaround now. This issue can be closed now @monoland

**Comment by fico7489** [comment] 2018-08-02 07:40
same here, @nasrulhazim thanks

**Comment by vesteves** [comment] 2018-08-13 18:04
great one @nasrulhazim <3

**Comment by dbudwin** [comment] 2018-08-17 20:45
This issue is still occurring for me using Laravel 5.7.  It appears that `league/oauth2-server` has not incorporated downstream changes from `defuse/php-encryption`.

**Comment by dbudwin** [comment] 2018-08-18 14:35
Sigh.  Ran `composer update` first thing this morning without changing anything and it worked 😒

**Comment by vlachmilan** [comment] 2018-08-30 12:32
@maranesi Sir, you are an angel sent by heaven.

**Comment by driesvints** [comment] 2018-10-15 12:39
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-10-15 12:39 UTC

**Comment by Qaisnezami** [comment] 2019-12-02 13:27
composer require paragonie/random_compat=~2.0
composer require laravel/passport=^7.0

**Comment by GordonOtieno** [comment] 2020-02-12 11:48
try this and let me know if it works composer require laravel/passport "4.0.*"

**Comment by JellyOnMa** [comment] 2020-02-20 10:02
Hi, I've had the same problem. Here is a fix, let me know if it works for anyone.
`composer create-project laravel/laravel="5.5.*” myProject`

**Comment by AmujoDotun** [comment] 2020-08-19 20:48
I experienced this same issue, what I did was to update the PHP version on my local server and everything was back o normal

**Comment by falgunshah7** [comment] 2020-09-23 11:59
I have update my laravel project 6 to 7 but I had same problem. I have fixed this and the steps in below. Hope this will be help.
In my case I have followed these steps.
-> Made changes in composer.json
laravel/framework to ^7.0
nunomaduro/collision to ^4.1
phpunit/phpunit to ^8.5
laravel/tinker to ^2.0
facade/ignition to ^2.0
and 
laravel/ui to ^2.0

-> And then changes in **App\Exceptions\Handler** class **Throwable** interface **instead** of Exception instances
public function report(Throwable $exception); // replace Exception with Throwable
public function render($request, Throwable $exception); // replace Exception with Throwable

run > composer update 

Done..!!
Application has been updated

**Comment by meetrp9989** [comment] 2022-02-15 05:55
Problem 1
    - laravel/passport[v9.0.0, ..., v9.2.2] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but the package is fixed to 7.4.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/passport[v9.3.0, ..., v9.3.1] require illuminate/auth ^6.0|^7.0 -> found illuminate/auth[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - laravel/passport[v9.3.2, ..., 9.x-dev] require illuminate/auth ^6.18.31|^7.22.4 -> found illuminate/auth[v6.18.31, ..., 6.x-dev, v7.22.4, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravel/passport ~9.0 -> satisfiable by laravel/passport[v9.0.0, ..., 9.x-dev].

**Comment by asifmasoodbutt** [comment] 2023-04-25 01:17
I am using Laravel version 10, and I faced the same issue. I ran the following command and it worked for me.
```php
composer require laravel/passport -W
``` 
I hope it would help someone if confronted with this error.

**Comment by Jitendrap67** [comment] 2023-05-20 03:54
run command:  composer require laravel/passport  --with-all-dependencies
