### ISSUE TITLE
Laravel 5.4 passport not working when my composer updating league/oauth2-server from v5.1.4 to v5.1.5

### ISSUE THREAD

**Issue by reachsampath** [laravel/passport#433] opened 2017-07-13 13:12 UTC
Hi I am implementing a php project with Laravel 5.4 framework. and i am using passport package to provide authentication to the apii's in project and it is working fine.

When i am doing composer update in my dependencies
league/oauth2-server from v5.1.4 is updating to league/oauth2-server from v5.1.5
then suddenly functionality related to passport is not working and throwing errors with 500 status.

while updating composer it is updating the league/oauth2-server from v5.1.4 to v5.1.5
![image_8k](https://user-images.githubusercontent.com/28009914/28167877-d445fac2-67fa-11e7-891e-450ed95b9208.png)

and after updating composer while accessing the api with login credentials it is throwing the error like below with 500 status

![image_h3](https://user-images.githubusercontent.com/28009914/28167903-e827cf34-67fa-11e7-84a8-f233175598b9.png)

How can i fix this. please suggest me if any solution.
Thanks in Advance.

**Comment by k1m0ch1** [comment] 2017-07-14 13:21
I think this related with this https://github.com/laravel/passport/issues/432

try updating to  v1.0.18

**Comment by Ecareyu** [comment] 2017-07-18 02:15
try to update the passport version in composer.json to 3.0

**Comment by alexbilbie** [comment] 2017-07-19 17:35
Duplicate of #432

**Closed by alexbilbie** 2017-07-19 17:35 UTC
