### ISSUE TITLE
How to get authenticated client by Client Credentials Grant ?

### ISSUE THREAD

**Issue by bravist** [laravel/passport#547] opened 2017-10-27 07:37 UTC
Like the file [CheckClientCredentials.php](https://github.com/laravel/passport/blob/4.0/src/Http/Middleware/CheckClientCredentials.php)

```php
 /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  mixed  ...$scopes
     * @return mixed
     * @throws \Illuminate\Auth\AuthenticationException
     */
    public function handle($request, Closure $next, ...$scopes)
    {
        $psr = (new DiactorosFactory)->createRequest($request);
        try {
            $psr = $this->server->validateAuthenticatedRequest($psr);
        } catch (OAuthServerException $e) {
            throw new AuthenticationException;
        }
        $this->validateScopes($psr, $scopes);
        return $next($request);
    }
```

why not add `$psr` to `$request` object when get authenticated client id in controller, like this 

```php
 $psr = $this->server->validateAuthenticatedRequest($psr);

$request->client = $psr
```

**Comment by bravist** [comment] 2017-10-27 08:00
this is a avaliable function
https://github.com/laravel/passport/issues/124

**Comment by driesvints** [comment] 2018-10-16 15:33
Heya, thanks for sending this in. I agree that this can be useful. I've marked this as a feature request. Feel free to send in a PR to master.

**Comment by driesvints** [comment] 2018-10-22 08:30
I'm going to close this as this is a duplicate of https://github.com/laravel/passport/issues/143. Please follow the discussion there.

**Closed by driesvints** 2018-10-22 08:30 UTC
Labels: feature request

**Comment by driesvints** [comment] 2018-10-22 08:56
Gonna close this one as it's a duplicate of https://github.com/laravel/passport/issues/143. Let's continue the discussion there.
