### ISSUE TITLE
Client credentials has no user attached

### ISSUE THREAD

**Issue by jeffsrepoaccount** [laravel/passport#578] opened 2017-12-14 17:22 UTC
I'm not sure if this issue actually belongs in laravel/passport, or if it belongs in thephpleague/oauth2-server, or if it belongs in lcobucci/jwt.

I want to have a single set of routes that any valid token obtained through any grant will have access. When I made the client credentials client, I made sure to associate the `oauth_client` with a user_id of a system user. As indicated in #334 , the claim put in the JWT token for `sub` (later pulled out by the league's resource server as the attribute `oauth_user_id`) is an empty string. I would expect this to be equal to the user ID that I set on the client credentials' client I created. Additionally, if only using the `CheckClientCredentials` middleware, API tokens created via password grant also exhibit this same behavior.

If I am understanding what `TokenGuard` is doing, _any_ `OAuthServerException` is immediately swallowed and dispatched to the exception handler, without possibility of catching it. This behavior disallows putting multiple middleware into a route group for the sake of validating access tokens according to different grant flows.

Using laravel/passport, am I forced to have a completely different set of routes using different middleware in order to validate both client credentials as well as password grant tokens? Is there another way to inject the client's user_id property into the proper claim on the token?

**Comment by driesvints** [comment] 2018-10-16 14:53
Closing this as a duplicate of https://github.com/laravel/passport/issues/143

**Closed by driesvints** 2018-10-16 14:53 UTC
