### ISSUE TITLE
v11.3 introducing a breaking change due to PR #1577 

### ISSUE THREAD

**Issue by RobinBertilsson** [laravel/passport#1610] opened 2022-12-22 09:40 UTC
- Passport Version: 11.3.0
- Laravel Version: 9.36.4
- PHP Version: 8.1.13

### Description:
As of version [11.3.0](https://github.com/laravel/passport/releases/tag/v11.3.0) a new promt feature was introduced.
This throws an AuthenticationException, which by default redirects to `route('login')`.

If you don't override the `unauthenticated` method in `app/Exceptions/handler.php` (which we didn't) this will redirect you to `/login`. Previosly we where able to rely on `app/Http/Middleware/Authenticate.php`, which is also what's covered in [Laravel's documentation](https://laravel.com/docs/9.x/authentication#redirecting-unauthenticated-users).

I'm not sure if this classifies as a breaking change, but if you follow Laravel's documentation, i think you quite often end up with a solution that only specifies your login route in the `Authenticate.php` middleware, and not by overriding the `unauthenticated` method in the exception handler. Which makes stuff break with just a minor package update, which is not ideal.

**Comment by driesvints** [comment] 2022-12-22 11:10
Heya, thanks for reporting. Ping @hafezdivandari what are your thoughts here?

**Comment by hafezdivandari** [comment] 2022-12-22 11:58
Duplicate of #1598 
Related PR: #1599

**Comment by driesvints** [comment] 2022-12-22 11:59
Seems like we won't be changing anything here @RobinBertilsson sorry. Thanks @hafezdivandari

**Closed by driesvints** 2022-12-22 11:59 UTC
Labels: needs more info
