### ISSUE TITLE
API Auth on multiple Model

### ISSUE THREAD

**Issue by ravigaudani** [laravel/passport#522] opened 2017-09-21 11:29 UTC
Please help me to grant and authenticate using Bearer. On single user model its work perfectly, but I also need to client login on client model. Token granted for client but returns Unauthenticated every time.
I tried https://github.com/laravel/passport/issues/161 but no luck.

**Comment by iamriajul** [comment] 2018-09-17 13:44
This might help:

My AdminAPI Url: https://example.com/api/login
My Customer API Url: https://example.com/api.customer/login

adding this to any ServiceProvider (I have added in RouteServiceProvider.php before custom route)
`        // Fix/Support for multiple user with different table by changing provider on customer-api circumstances

        Config::set('auth.guards.api.provider', request()->input('provider', starts_with(request()->path(), 'api.customer') ? 'customers' : 'users'));`

and must add your custom provider in providers array in config/auth.php
`        'customers' => [
            'driver' => 'eloquent',
            'model' => App\Customer::class,
        ],`

**Comment by driesvints** [comment] 2018-10-15 12:09
Duplicate of https://github.com/laravel/passport/issues/161

**Closed by driesvints** 2018-10-15 12:09 UTC

**Comment by clunkylion** [comment] 2020-06-25 02:11
Hello, I need help, I have the same problem, I am already stressed :(  !! 
How did they solve it?
