### ISSUE TITLE
Error when install passport with laravel 5.6

### ISSUE THREAD

**Issue by ayman1-elmalah** [laravel/passport#777] opened 2018-07-24 20:39 UTC
This error happens when i'm trying to install passport with laravel 5.6
![3242536789](https://user-images.githubusercontent.com/37438338/43164777-5ff526be-8f92-11e8-8a5a-27bc8648a717.PNG)

**Comment by Sephster** [comment] 2018-07-24 21:16
Duplicate of #774

**Comment by driesvints** [comment] 2018-10-15 12:37
Indeed a duplicate of #774

**Closed by driesvints** 2018-10-15 12:37 UTC
