### ISSUE TITLE
Multiple findForPassport ? e.g Login with username and phone number

### ISSUE THREAD

**Issue by hamidafghan** [laravel/passport#1023] opened 2019-05-22 14:21 UTC
I have tried the ``` findForPassport ```. It is good if there is just one field instead of the default but I want to log in either with ```username or phone number ```. For the basic login what I did is 
```
 // Login Controller 
public function __construct()
    {
        $this->middleware('guest')->except('logout');

        $this->username = $this->findUsernameOrPhone();
    }

public function findUsernameOrPhone()
    {
        $login = request()->input('username');

        $fieldType = Str::startsWith($login, '07') ? 'phone' : 'username';

        request()->merge([$fieldType => $login]);

        return $fieldType;
    }

/**
     * Get phone property.
     *
     * @return string
     */
    public function phone()
    {
        return $this->username;
    }

    /**
     * Get username property.
     *
     * @return string
     */
    public function username()
    {
        return $this->username;
    }
```

So here I can log in with username and phone number. How it is possible for the passport too.

**Comment by driesvints** [comment] 2019-05-27 13:44
This seems like a duplicate of https://github.com/laravel/passport/issues/982 and https://github.com/laravel/passport/issues/161

**Closed by driesvints** 2019-05-27 13:44 UTC
