### ISSUE TITLE
scope/s auth checks throw dedicated error

### ISSUE THREAD

**Issue by di5abled** [laravel/passport#198] opened 2016-11-20 21:14 UTC
Hello,

when a user can't access a given endpoint due to the scope/s middleware I want to inform him which scope/s failed. Probably the best way would be to make an own exception extending the current AuthenticationException. Then I could check for this in the exception handler and build an response containing all needed infos.

Is this something we could/should handle via passport or should I just create my own middleware?

**Comment by craigpaul** [comment] 2016-11-21 05:55
Seems like a good idea to me, could be an InvalidScopesException that can be passed an array or string of the scope(s). You could make a PR and see what you come up with, seems like something Passport could benefit from.

Keep in mind that the exception handler only triggers report, not render so you wouldn't be able to catch it in the main applications handler using this custom exception. Passport would have to have a custom generic response that would list out the scopes.

**Comment by anhducbkhn** [comment] 2016-11-23 03:27
scope failed for me.
Also, when I input an incorrect access_token, it does  not response a json message, it respon a html page.
The issue is in CheckScopes:

class CheckScopes
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  array  $scopes
     * @return \Illuminate\Http\Response
     */
    public function handle($request, $next, ...$scopes)
    {
        if (! $request->user() || ! $request->user()->token()) {
            throw new AuthenticationException;
        }

        foreach ($scopes as $scope) {
            if (! $request->user()->tokenCan($scope)) {
                throw new AuthorizationException;
            }
        }

        return $next($request);
    }
}

$request->user() will be null if access_token is incorrect.

**Comment by themsaid** [comment] 2016-11-23 14:03
@di5abled are you willing to make a PR?

**Comment by craigpaul** [comment] 2016-11-24 00:38
@di5abled @themsaid I had some time so I went ahead and made a PR, but feel free to make another if it's not what you were thinking 👍

**Comment by craigpaul** [comment] 2016-11-30 23:05
@di5abled As the PR was merged, I hope that helps with your use case. Please don't forget to close this issue :) thanks!

**Comment by themsaid** [comment] 2016-12-01 19:20
@craigpaul  👍♥️

**Closed by themsaid** 2016-12-01 19:20 UTC
