### ISSUE TITLE
"Call to a member function forceFill() on null" Error when calling $user->createToken('Foo')->accessToken

### ISSUE THREAD

**Issue by tomothumb** [laravel/passport#713] opened 2018-05-17 12:30 UTC
Same issue as the one below link.
https://laracasts.com/discuss/channels/laravel/call-to-a-member-function-forcefill-on-null-error-when-calling-user-createtokentoken-accesstoken

This happens sometimes. It's not every time.
Do you have any idea of reason and solution?

```
/www/vendor/laravel/passport/src/PersonalAccessTokenFactory.php

    public function make($userId, $name, array $scopes = [])
    {
        $response = $this->dispatchRequestToAuthorizationServer(
            $this->createRequest($this->clients->personalAccessClient(), $userId, $scopes)
        );
 
        $token = tap($this->findAccessToken($response), function ($token) use ($userId, $name) {
            $this->tokens->save($token->forceFill([
                'user_id' => $userId,
                'name' => $name,
            ]));
        });
 
        return new PersonalAccessTokenResult(
            $response['access_token'], $token
        );
    }
```

**Comment by driesvints** [comment] 2018-10-15 14:17
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by Qlwentt** [comment] 2018-10-29 20:00
what laravel update is supposed to fix this? I'm having the same issue. I'm on laravel 5.6.39

**Comment by Ravi1990** [comment] 2018-10-30 04:56
Yes i have also laravel 5.6.39, same issue here. The solution mention above is this https://github.com/laravel/passport/issues/467. But you look in vendor mention fix is already there, but issue still persist. 
In my code on login it generate token and provide access, now user has to hit login 2-3 times to get into login. Because it work after some try.

**Comment by Ravi1990** [comment] 2018-10-30 05:39
Also i like to mention here that it is working fine in my local system, issue occurs on live server on production. May be some issue with timing, production server is fast so it try to executing something which is not initialize may be.

**Comment by Qlwentt** [comment] 2018-10-30 13:17
Yes, same here. this error is only happening to me on a production server about 15-20 times per day. It does not happen every single time a user tries to log in, only intermittently.

**Comment by Ravi1990** [comment] 2018-11-02 12:53
> I'll try to look at this at a later time. In the meantime feel free to check if you can provide a failing test.

Any Update on this?

**Comment by driesvints** [comment] 2018-11-05 10:36
@Ravi1990 still haven't found time yet. Can you please try upgrading to Laravel 5.7 and the latest Passport version and see if the problem persists?

**Comment by Ravi1990** [comment] 2018-12-03 10:10
> @Ravi1990 still haven't found time yet. Can you please try upgrading to Laravel 5.7 and the latest Passport version and see if the problem persists?

upgraded to Laravel 5.7 still same issue.

**Comment by Ravi1990** [comment] 2018-12-06 04:57
Hi, i have found the issue it was because of Read & Write Connections i am using and was not using " 'sticky'=>true", so it write from one connection and read from another connection which was not updated as it was happening so fast on server.
 So it gives "forceFill() on null" as $token is not found on read connection. So the **solution** for me was to use **'sticky'=>true** in database config.

**Comment by driesvints** [comment] 2019-01-11 16:49
@Ravi1990 okay

Please @Qlwentt let me know if this was also the case for you.

**Closed by driesvints** 2019-01-11 16:49 UTC
Labels: bug

**Comment by Qlwentt** [comment] 2019-01-11 18:02
Sorry for the late reply! Yes that was the same issue me

**Comment by loktarjugg** [comment] 2019-04-27 02:37
same issue here
i may have found the cause of the problem, before creating the token, I deleted the old token

now i delete this code and it works.
![image](https://user-images.githubusercontent.com/3970144/56843773-68ae7880-68d8-11e9-9036-b06e71b3d07f.png)

**Comment by yogeshkoli** [comment] 2019-05-30 10:12
I also had the error on Laravel 5.6 using MySQL 5.7.  so to describe main reason behind this cause is Read & Write Connections. 
Solution: Add `'sticky' => true,` to you database.php config file. and you are good to go.

**Comment by agamyrat301** [comment] 2019-10-12 13:02
wqdqwdqwdqwdqd

**Comment by MohitVisions** [comment] 2020-01-30 13:23
My file have already 'sticky' => true but still show same error i am using laravel 6 .

**Comment by tsaini530** [comment] 2020-09-02 06:52
I added  'sticky' => true in my datase.php  file but still, show the same error. I am using Laravel 7.21 and Postgres

**Comment by PhamBaTrungThanh** [comment] 2021-04-20 10:19
I'm on Laravel 5.4 and MySQL 5.7 and this error still occur, but very rarely (like once/twice a month).

Does anyone have the explaination for this?

**Comment by jesiljose-bridge** [comment] 2024-04-02 09:28
Same issue here as well
