### ISSUE TITLE
Cannot Custom Handle `Laravel\Passport\Exceptions\OAuthServerException` in Laravel 11

### ISSUE THREAD

**Issue by rulim34** [laravel/passport#1756] opened 2024-06-22 14:44 UTC
### Passport Version

12.2.0

### Laravel Version

11.10.0

### PHP Version

8.2.19

### Database Driver & Version

MariaDB docker

### Description

I tried to custom render `Laravel\Passport\Exceptions\OAuthServerException` on Laravel 11 as per [the documentation](https://laravel.com/docs/11.x/errors#rendering-exceptions). But it doesn't work and just return the default JSON response.
![image](https://github.com/laravel/passport/assets/48084535/a66819ed-dcae-4501-b337-9eece5704e05)
![image](https://github.com/laravel/passport/assets/48084535/6e5a3e89-a19a-49e6-bace-dabb9a38ee93)
![image](https://github.com/laravel/passport/assets/48084535/83dd9c77-fbaa-4eab-b0de-de9da934d264)

### Steps To Reproduce

1. Install Laravel 11
2. Install Passport 12
3. Setup custom render

**Comment by driesvints** [comment] 2024-06-24 18:13
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by rulim34** [comment] 2024-06-24 23:44
Hi,

Sure, here is the repository: https://github.com/rulim34/laravel-oauth-exception.git

**Comment by driesvints** [comment] 2024-06-28 09:12
I wonder what happened here because this should be possible after @matt-allan's PR here: https://github.com/laravel/passport/pull/1066. But maybe something broke with Laravel 11. Would appreciate any help here...

**Comment by hafezdivandari** [comment] 2024-06-30 07:17
You may check PR #1763

**Comment by codespearhead** [comment] 2024-07-04 18:55
@rulim34 https://github.com/laravel/passport/pull/1763 was merged into https://github.com/laravel/passport/tree/13.x two days ago. Can you close this issue?

**Comment by driesvints** [comment] 2024-07-04 19:07
Ty!

**Closed as completed** 2024-07-04 19:06 UTC
Labels: bug, help wanted

**Comment by jrdnrc** [comment] 2025-06-17 07:54
@hafezdivandari @driesvints sorry to reopen a conversation nearly a year old, I'm a little stuck and I _think_ this may be the issue 🤔 

When a route is run in Laravel, it catches the `HttpResponseException` and immediately returns the contained response - bypassing any exception handling code.

See: https://github.com/laravel/framework/blob/12.x/src/Illuminate/Routing/Route.php#L205-L218

This feels like a regression - in Passport v12, I was able to catch and transform the exception into something matching the format of our stacks errors but I don't think I can do that any more (without a global middleware inspecting each response).

I understand that according to the OAuth RFC this is fine - the defined error messages are part of the standard - and if Passport is aiming to enforce that, then that makes sense. But it seems like the opposite is true?

I'd be very grateful if some light could be shed on this, and happy to think about a PR if y'all feel that allowing the developer to catch and transform these exceptions is something within the scope of Passport.

Equally I could be being a big dumb dumb and missing something obvious around how to catch and transform these exceptions.

**Comment by akyrey** [comment] 2026-03-03 07:34
> [@hafezdivandari](https://github.com/hafezdivandari) [@driesvints](https://github.com/driesvints) sorry to reopen a conversation nearly a year old, I'm a little stuck and I _think_ this may be the issue 🤔
> 
> When a route is run in Laravel, it catches the `HttpResponseException` and immediately returns the contained response - bypassing any exception handling code.
> 
> See: https://github.com/laravel/framework/blob/12.x/src/Illuminate/Routing/Route.php#L205-L218
> 
> This feels like a regression - in Passport v12, I was able to catch and transform the exception into something matching the format of our stacks errors but I don't think I can do that any more (without a global middleware inspecting each response).
> 
> I understand that according to the OAuth RFC this is fine - the defined error messages are part of the standard - and if Passport is aiming to enforce that, then that makes sense. But it seems like the opposite is true?
> 
> I'd be very grateful if some light could be shed on this, and happy to think about a PR if y'all feel that allowing the developer to catch and transform these exceptions is something within the scope of Passport.
> 
> Equally I could be being a big dumb dumb and missing something obvious around how to catch and transform these exceptions.

I do have the same issue. In previous Passport version I was able to customize the response, but with version 13.x it is no longer possible.
Is there something we are missing?

**Comment by MarcEspiard** [comment] 2026-04-30 06:17
> [@hafezdivandari](https://github.com/hafezdivandari) [@driesvints](https://github.com/driesvints) sorry to reopen a conversation nearly a year old, I'm a little stuck and I _think_ this may be the issue 🤔
> 
> When a route is run in Laravel, it catches the `HttpResponseException` and immediately returns the contained response - bypassing any exception handling code.
> 
> See: https://github.com/laravel/framework/blob/12.x/src/Illuminate/Routing/Route.php#L205-L218
> 
> This feels like a regression - in Passport v12, I was able to catch and transform the exception into something matching the format of our stacks errors but I don't think I can do that any more (without a global middleware inspecting each response).
> 
> I understand that according to the OAuth RFC this is fine - the defined error messages are part of the standard - and if Passport is aiming to enforce that, then that makes sense. But it seems like the opposite is true?
> 
> I'd be very grateful if some light could be shed on this, and happy to think about a PR if y'all feel that allowing the developer to catch and transform these exceptions is something within the scope of Passport.
> 
> Equally I could be being a big dumb dumb and missing something obvious around how to catch and transform these exceptions.

@driesvints Any chance you could have a quick look at this please? We're upgrading to Laravel 13 and have to upgrade Passport to latest. Custom handling of OAuthServerException is no longer possible because it now extends HttpResponseException and is handled automatically in the Route. This is actually a breaking change for us, our apps are relying on the response being formatted a certain way and this would break backwards compatibility internally.

Is there something we are missing? Happy to make a PR if you have any pointers on what would be an acceptable solution.

Cheers,

**Comment by MarcEspiard** [comment] 2026-04-30 06:18
@akyrey @jrdnrc You guys ever found a solution for this? I know you could go the middleware route but that seems clunky.

**Comment by akyrey** [comment] 2026-04-30 08:51
> @akyrey @jrdnrc You guys ever found a solution for this? I know you could go the middleware route but that seems clunky.

Nope, I had to go the middleware route but I agree that it's clunky
