### ISSUE TITLE
passport:install breaking change

### ISSUE THREAD

**Issue by sajadshouli** [laravel/passport#1784] opened 2024-09-05 16:52 UTC
### Passport Version

12

### Laravel Version

11

### PHP Version

8.2

### Description

the passport package version 12 made a breaking change by replacing the passport:install to passport:keys and passport:client

these changes are fine for me but I have a problem in my testing area since I use `orchestra/testbench` package for package development

in my setUp function in the test class

I make passport keys to test some features like authentication like this

```php
            // Artisan::call('passport:install');
            Artisan::call('passport:keys');
            Artisan::call('passport:client --personal --name=test');
            Passport::tokensCan([
                'is-test'       => 'token belongs to test',
                'is-user'       => 'token belongs to an user',
            ]);
```

in the new version of Laravel or passport you must publish the migrations(in the old version it was not necessary) so for the first time when I run the test it throw an exception that the oauth tables do not exist
so I have to run passport:install to publish tables for the first time 

![image](https://github.com/user-attachments/assets/1d36b99e-360d-4f60-ae05-20995339eddb)

and I have to comment on the passport:install command since for the second time my tests run it throws the oauth table already exists since the orchestra  or passport publish it again with other names

![Screenshot 2024-09-05 200918](https://github.com/user-attachments/assets/5024eb07-9f4a-4ebc-88fd-9d951422071e)

And I do not know if to report this bug on `orchestra/testbench` repo or if it is a problem with passport since the orchestra is a wrapper of Laravel framework

@crynobone

### Steps To Reproduce

make a test

**Comment by hafezdivandari** [comment] 2024-09-05 20:37
Duplicate of #1729 and #1781

**Comment by driesvints** [comment] 2024-09-06 07:05
Please see the above. Thanks @hafezdivandari

**Closed as completed by driesvints** 2024-09-06 07:05 UTC
