### ISSUE TITLE
Add more custom information to the JWT

### ISSUE THREAD

**Issue by leroy0211** [laravel/passport#676] opened 2018-03-21 13:14 UTC
Is there any way of adding custom public claims to the JWT instead than the defaults?

Currently the payload of the JWT holds the default claims  `aud`, `jti`, `iat`, `nbf`, `exp`, `sub`, and a single single custom public claim `scopes`. But what if we want the first name to be added to the JWT claims too?

As described in the documentation:  https://tools.ietf.org/html/rfc7519#section-4.2

**Comment by genyded** [comment] 2018-03-27 13:51
Yes - please consider this! Without this is requires 2 API calls (one to get the token and one to get the user info) when if the payload had the ability to contain the user info only one API call would be needed. Additionally almost all other Passport/JWT implementations support this.

One of the key points for using this is to be able to pass custom data in the token.

**Comment by atrauzzi** [comment] 2018-07-02 02:12
Yeah, this is definitely needed so that I can add organization and tenant information as claims to the token.  There's no real way in a stateless situation to pull that information up correctly without putting the information elsewhere on the wire.

**Comment by ali-syr** [comment] 2018-10-06 10:33
This feature is really needed,
My use case , access token  for mobile application  should include  mobile device id , so for example when user log out from mobile app ,server just stop push notification for just that mobile

**Comment by driesvints** [comment] 2018-10-16 08:36
Going to close this as it's a duplicate of #94.

**Closed by driesvints** 2018-10-16 08:36 UTC
