### ISSUE TITLE
Private pusher channels with a Client Credentials Grant client from Laravel Passport

### ISSUE THREAD

**Issue by no0by5** [laravel/passport#1166] opened 2020-01-13 17:06 UTC
- Passport Version: 8.2.0
- Laravel Version: 6.10.1
- PHP Version: 7.2.19

### Description:
You are not able to use a private pusher channel with a passport Client Credentials Grant client.
That's because of this check in src\Illuminate\Broadcasting\Broadcasters\PusherBroadcaster.php:
```php
if ($this->isGuardedChannel($request->channel_name) &&
    !$this->retrieveUser($request, $channelName)) {
    throw new AccessDeniedHttpException();
}
```
The call to `isGuardedChannel(...)` returns true, because it's a private channel. The call to `retrieveUser(...)` returns false, because there is no logged in user when you are using a Client Credentials Grant client from passport, so the exception is thrown.<br>

### Steps To Reproduce:
1. Create a Client Credentials Grant client for passport with `php artisan passport:client --client`.
2. Add a Broadcast channel to `routes/channels.php`
```php
Broadcast::channel('user-scanned', function ($user) {
    return true;
});
```
3. Add```Broadcast::routes([
    'middleware' => 'auth.client',
]);```
to the `boot` method of the `BroadcastServiceProvider`.
4. Make a request to `/broadcasting/auth` with an access_token aquired from the client created in step 1

**Comment by driesvints** [comment] 2020-01-14 13:11
Transferred to the passport repo. Please indicate the passport version you're using.

**Comment by no0by5** [comment] 2020-01-15 09:03
I'm using passport version 8.2.0

**Comment by driesvints** [comment] 2020-01-15 12:43
We unfortunately don't support Passport in combination with broadcasting. We have a dedicated JS library to work with broadcasting which you can use: https://github.com/laravel/echo

**Closed by driesvints** 2020-01-15 12:43 UTC
Labels: needs more info

**Comment by matheusb-comp** [comment] 2020-03-05 04:05
> We unfortunately don't support Passport in combination with broadcasting. We have a dedicated JS library to work with broadcasting which you can use: https://github.com/laravel/echo

I don't understand. The example from @no0by5 happens when using the suggested library Laravel Echo:
```
import Echo from 'laravel-echo'
window.Echo = new Echo({
  broadcaster: 'pusher',
  key: process.env.MIX_PUSHER_APP_KEY,
  cluster: process.env.MIX_PUSHER_APP_CLUSTER,
  authEndpoint: 'broadcasting/auth',
  auth: {
    headers: {
      Authorization: 'Bearer ' + token
    }
  }
});
window.Echo.private('user-scanned').listen('event', (ev) => console.log(ev));
```

Since the channel is `private`, it requires [authorization](https://laravel.com/docs/5.8/broadcasting#authorizing-channels). And the authorization is supported when using any other grants with Passport. For example, if the broadcast route is [defined](https://laravel.com/docs/5.8/broadcasting#defining-authorization-routes) with:
```
Broadcast::routes([ 'middleware' => 'auth:api' ]);
```
It will work as expected, when the Bearer token is correct, because the `retrieveUser()` function will return the user identified by the token.

The problem is that when a [Client Credential Grant](https://laravel.com/docs/6.x/passport#client-credentials-grant-tokens) is used, the token is not associated to any user, since:
> The client credentials grant is suitable for machine-to-machine authentication

I imagine this check is in place to prevent the `$user` variable being null in the [authorization callback](https://laravel.com/docs/5.8/broadcasting#defining-authorization-callbacks) in the `routes/channels.php` file:
```
Broadcast::channel('user-scanned', function ($user) {
  return true;
});
```

But is the check really necessary? Just removing it allows machine-to-machine access to the Broadcast system, and the `$user` variable being `null` in the callback would be expected by anyone using this Passport grant.
