### ISSUE TITLE
Client Credentials Grant Tokens problem

### ISSUE THREAD

**Issue by boneq** [laravel/passport#767] opened 2018-07-17 16:24 UTC
Hello:
Why any key can request Client Credentials Grant Tokens, I don't really understand that I have 2 servers one is Oauth, the other is appserver, you can get token, I just want a specific appserver to operate the data on Oauth, rather than let all oauth_clients can use Client Cred Entials Grant Tokens to operate the API on my Oauth

**Comment by driesvints** [comment] 2018-10-15 13:03
Closing this as a duplicate of #691

**Closed by driesvints** 2018-10-15 13:03 UTC
