### ISSUE TITLE
"storage/oauth-private.key" does not exist or is not readable.

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/passport#418] opened 2017-07-03 10:54 UTC
Hi, today I updated composer and I got this error:
`Operation failed: Operation not permitted`

I have resolved this probem by running the following commands:
`chmod 600 storage/oauth-private.key`
`chmod 600 storage/oauth-public.key`

But then I got the following error:
`"storage/oauth-private.key" does not exist or is not readable`

Thanks for help

**Comment by alexbilbie** [comment] 2017-07-04 08:30
@siarheipashkevich you need to ensure that the PHP process owns the private and public keys

**Comment by siarheipashkevich** [comment] 2017-07-04 08:33
@alexbilbie could you please help me how can I check it?

**Comment by SmileYuhao** [comment] 2017-07-04 08:35
I think you didn't correctly install `passport`.

Please run this command:

```
php artisan passport:install
```

**Comment by siarheipashkevich** [comment] 2017-07-04 08:36
@SmileYuhao I ran this command and I have installed keys.

**Comment by siarheipashkevich** [comment] 2017-07-04 08:41
@alexbilbie I updated composer packages in the Homestead machine and I am not getting any errors, but in my local machine I get this error. I'm afraid that it will break my prod.

**Comment by bassco** [comment] 2017-07-04 12:32
The file permission changes introduced in 2.0.11 have been disastrous for us too. We host our laravel containers and publish the shared oauth keys via secret files using volume mounts in a kubernetes cluster.

The website runs under user _www-data_, but the secret files are mounted and owned by _root_.

We are pegging our application at 2.0.10 as we are unable to change the ownership of the files.

**Comment by jspicee** [comment] 2017-07-04 13:00
Same issue

**Comment by lomby** [comment] 2017-07-04 15:22
We are also experiencing this issue over the last couple of days. The only workaround for us was to set the owner of these two files to www-data manually when they have always been root previously.

**Comment by maurice-ellis** [comment] 2017-07-04 17:15
The version 5.1.4 of \League\OAuth2\Server has a change that needs to be update in Passport.

https://oauth2.thephpleague.com/v5-security-improvements/

**Comment by shailesh87** [comment] 2017-07-05 07:36
I am also facing same issue after composer update.

**Comment by andrefigueira** [comment] 2017-07-06 10:48
Same issue here after a composer update

**Comment by iget-esoares** [comment] 2017-07-07 01:55
This issue is causing big problems here.

The file should be owned by `www-data` when accessing on web, and by `myuser` when accessing artisan tinker, because it try to run `chmod`, that can only be called by file owner (or root).

**Comment by Wolg** [comment] 2017-07-07 05:01
Having the same issue with Envoyer deployment. 
when deploying and performing php artisan optimize we need those files to belong deployment user (ec2-user on aws). But it will break entire application 'cause when accessing on web it should belong to web-server user (nginx).

**Comment by andrefigueira** [comment] 2017-07-07 08:48
@iget-esoares from what I can see in the code, it only attempts to run the chmod when the permissions are incorrect, so you could circumvent by having the permissions set at a higher level, for example your provisioning tool or deployment tool.

**Comment by shailesh87** [comment] 2017-07-10 12:41
In  the centos linux the command **chown  apache:apache /storage -R** work for me.

**Comment by libasoles** [comment] 2017-07-10 18:50
Well, according to `/vendor/league/oauth2-server/src/CryptKey.php` both files must be _chown_ to http server (nginx/apache/whatever) and permissions set to 0600. Like: 

```
sudo chmod 0600 storage/oauth*
sudo chown http:http storage/oauth*
```

Personally I dislike this. it breaks our existing code and forces me to set the user (not only the group) to http server.

**Comment by libasoles** [comment] 2017-07-10 18:58
Things are being quite in _phpleague_ repo:
https://github.com/thephpleague/oauth2-server/issues/760

**Comment by alexbilbie** [comment] 2017-07-11 06:39
I have released [`5.1.5`](https://github.com/thephpleague/oauth2-server/releases/tag/5.1.5) which replaces the hard errors with notices and deprecation warnings.

It is correct behaviour that the key should be owned by the server process to prevent possibility of token forgery by replacing the server’s public key or leakage of the key by an attacker or rogue other process.

**Comment by andersonamuller** [comment] 2017-07-11 09:27
Does anyone have a fix for this case?
- Container PHP-FPM runs on `www-data`;
- OAuth keychain are Kubernetes secrets mounted and owned by root;

AFAIK, you cannot change that last part.

See also https://github.com/laravel/passport/issues/418#issuecomment-312866308

**Comment by vdjkelly** [comment] 2017-07-12 10:00
> chmod(/var/www/sanidad/storage/oauth-public.key): Operation failed: Operation not permitted

help me

**Comment by ryankazokas** [comment] 2017-07-13 03:23
@andrefigueira i changed ownership of the keys to www-data and the permissions to 0600  within the docker container and now I'm getting an error prior to that when it is trying to find if the file is readable?  Has this been happening to anyone else? Even if i keep the perms at 0600 and change the user;group back to root:root there is the same issue.

**Comment by libasoles** [comment] 2017-07-13 03:31
@ryankazokas it's not root:root, but _server:server_ (meaning apache2:apache2, http:http, or whatever user you have in your server)

**Comment by ryankazokas** [comment] 2017-07-13 03:57
@libasoles , you are correct, i was able to find the correct user/group combo for my apache2, but now I'm receiving:


> (1/1) ErrorExceptionYou must set the encryption key going forward to improve the security of this library - see this page for more information https://oauth2.thephpleague.com/v5-security-improvements/
> --
> in AuthorizationServer.php (line 142)
> at HandleExceptions->handleError(16384, 'You must set the encryption key going forward to improve the security of this library - see this page for more information https://oauth2.thephpleague.com/v5-security-improvements/', '/var/www/vendor/league/oauth2-server/src/AuthorizationServer.php', 142,array('grantType' => object(AuthCodeGrant), 'accessTokenTTL' => object(DateInterval)))

i confirmed that the permissions are 0600.

```
-rw-------  1 laradock laradock  812 Jul 13 03:15 oauth-private.key
-rw-------  1 laradock laradock 3292 Jul 13 03:15 oauth-public.key
```

**Comment by libasoles** [comment] 2017-07-13 04:08
@ryankazokas Well, that's a basic step in Laravel. You must generate an APP_KEY and store it in your .env file. Use: `artisan key:generate`.

**Comment by ryankazokas** [comment] 2017-07-13 10:05
@libasoles i've done this, and just to reassure myself i did it again and still receive the same error. The error seems to be unrelated(although i'm not positive, so i can hack away at it and if i need a new issue thread for that or need to come back, I will go that route. Thanks!

**Comment by namelivia** [comment] 2017-07-13 10:21
@libasoles @ryankazokas The unset key that triggers the error is a property called `encryptionKey` and is on the following class `League\OAuth2\Server\AuthorizationServer`. The class has a setter method for that variable but I've looked through the code and I don't see any call for setting that property, so it stays as null and the error is triggered.

**Comment by ryankazokas** [comment] 2017-07-13 14:39
@namelivia yeah i saw why it was happening. Wasn't sure where or why it wasn't being set. What version are you using?

**Comment by indra1** [comment] 2017-07-13 15:18
@Wolg just update your envoyer to run chmod at the end to return oauth keys to www-data. I just got this error and i'm still stuck with it

**Comment by ryankazokas** [comment] 2017-07-13 21:43
@libasoles @namelivia 
I was able to fix this by updating to the newest version(3.0) of laravel\passport

https://github.com/laravel/passport/commit/6dc37eb5f8da996409ff041a8de62959dbba0cec

**Comment by Hao-Wu** [comment] 2017-07-14 02:59
Just a quick workaround for this issue, comment out line 142 in /league/oauth2-server/src/AuthorizationServer.php

```php
        if ($this->encryptionKey === null) {
            // @codeCoverageIgnoreStart
            //trigger_error(self::ENCRYPTION_KEY_ERROR, E_USER_DEPRECATED);
            // @codeCoverageIgnoreEnd
        }
```

But please keep in mind that, it is just a quick workaround to let the server work, but not a real fix. We are recommended to upgraded oauth2-server or modify keys.

**Comment by ryankazokas** [comment] 2017-07-14 03:12
@Hao-Wu i had to updgrade and modify the permissions of the keys because after I did composer update, it pulls in the newest version of 5.1.5 league/oauth2. This is problematic because laravel/passport  2.0.11  and below  due to not pass the key in the constructor when creating the authorizationServer.

**Comment by bbdangar** [comment] 2017-07-14 11:41
I am also facing the issue. If you look at the CryptKey.php, it says you must assign 0600 permission to the keys (line 51) and also it should be readable(line 43), to pass this condition you need to assign 0644 permissions to the keys. It fails in one of the conditions. The solution could be changing ownership of the keys. However, who I don't know who should be the owner of the keys.

For temporary You can comment line 48 to 68.

**Comment by namelivia** [comment] 2017-07-14 12:27
As @ryankazokas previously mentioned, seems to updating passport to 3.0 solved the issue.

**Comment by k1m0ch1** [comment] 2017-07-14 13:28
every time I set to the right owner, passport will reset the owner, please fix this wihtout I upgrading to 3.0 :(

**Comment by bbdangar** [comment] 2017-07-17 04:48
@namelivia mine is already on ^3.0, I mentioned above is in 3.0

**Comment by ryankazokas** [comment] 2017-07-17 16:45
@bbdangar Are you sure you are providing the 600 permissions to the correct user. They should be sufficient enough to pass the is_readable method. The same thing happened to me since I am running laradock and docker the user:group combo i needed was laradock:laradock

**Comment by bbdangar** [comment] 2017-07-18 04:55
`drwxrwxrwx  6 bbdangar bbdangar  4096 Jul 14 13:09 .
drwxrwxr-x 13 bbdangar bbdangar  4096 Jun  1 17:20 ..
drwxrwxrwx  6 bbdangar bbdangar  4096 Jun 16 18:24 app
drwxrwxrwx  2 daemon   daemon   81920 Jul 17 21:33 debugbar
drwxrwxrwx  6 bbdangar bbdangar  4096 May 11 18:12 framework
drwxrwxrwx  2 bbdangar bbdangar  4096 May 30 16:49 logs
-rw-r--r--  1 www-data www-data  3292 Jul 14 16:39 oauth-private.key
-rw-r--r--  1 www-data www-data   812 Jul 14 16:39 oauth-public.key
`
who is the correct user in this case? bbdangar?? I have tried to change ownership but didn't work. I got it working by modifying CryptKey.php

**Comment by etertime** [comment] 2017-07-19 07:57
@libasoles **The HTTP server settings owner can solve the problem.**,no problem, at least it can run

But the nginx server settings are ineffective, such as:

```
chmod 600 storage/oauth-p*
chown nginx:nginx storage/oauth-p*
```
The nginx here is the nginx server user, in the nginx.conf configuration

Result：
```
-rw------- 1 nginx nginx 3.2K Jul 19 15:03 oauth-private.key
-rw------- 1 nginx nginx  799 Jul 19 15:03 oauth-public.key
```

Key path "file:///var/www/NewDrugsSuperviseSystemApi/storage/oauth-private.key" does not exist or is not readable

@indra1 Have you tested the nginx server, please?
Who can solve this problem, someone upgraded to 3.0 ([#435](https://github.com/laravel/passport/issues/435)), or there are problems!

**Comment by libasoles** [comment] 2017-07-19 13:03
@etertime I run nginx but inside docker. For me is http:http and it works. Are you using virtualization?

And yes, you'll have to upgrade to Passport 3. No problems.

**Comment by alexbilbie** [comment] 2017-07-19 17:37
Please upgrade to Passport `3.0.*` to address these issues.

I've pushed a fix to the parent library so that there are no longer any hard errors being thrown if the key files doesn't have 600 permission

**Closed** 2017-07-19 17:40 UTC

**Comment by AbhijeetSomwanshi** [comment] 2017-08-02 11:51
I am getting the following error on upgrade of Passport "laravel/passport": "^3.0" Please help its on live server and urgent

chmod(/var/www/html/storage/oauth-private.key): Operation failed: Operation not permitted

**Comment by kmligue** [comment] 2017-08-05 08:17
Thanks @libasoles. It fixes my issue. In second command, I changed "http:http" to "www-data:www-data".

**Comment by coreation** [comment] 2017-08-07 20:12
@alexbilbie what about L5.3 users? Passport 3.0.* requires Illuminate packages for 5.4... I'm running Passport 1.0 at the moment.

**Comment by MrKriegler** [comment] 2017-09-06 09:17
If you are having this issue on mac then 

```
sudo chown _www:_www storage/oauth-*.key
```

Fixed my issue

**Comment by nadeemse** [comment] 2017-09-23 15:18
**sudo chown www-data:www-data storage/oauth-*.key** 
Saved my hours of effort 👍

**Comment by adangbryen** [comment] 2017-12-01 14:36
If the file is not exit use the following cmd
```php
php artisan passport:keys

**Comment by Braunson** [comment] 2017-12-19 20:47
I had this issue with Jenkins, turned out I just needed to add `php artisan passport:keys` into my deploy pipeline.

**Comment by hemorej** [comment] 2018-01-15 16:16
I'm on Heroku, I've generated the keys with `php artisan passport:keys` and set the permission to 600 but Passport still complains about the keys

**Comment by MrKriegler** [comment] 2018-01-15 16:34
@hemorej you must set the owner of the keys to your web server. On mac this helped me 

`sudo chown _www:_www storage/oauth-*.key`

_www is the apache user find yours and change the owner

**Comment by hemorej** [comment] 2018-01-15 17:17
@MrKriegler it's already set to the owner, with 600

**Comment by hotrush** [comment] 2018-03-13 13:04
I am using passport 5.0 with laravel 5.6. Of course i do not store this keys in vcs, and when i deploy the project i get this error at composer install stage. 

```
composer install --no-dev --prefer-dist -o

Loading composer repositories with package information
Installing dependencies from lock file
...
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In CryptKey.php line 45:
                                                                               
  Key path "file:///home/.../public_html/storage/oauth-private.key" does not exist or is not readable                                                  
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

Of course it does not exist, it does not generated yet!

**Comment by hshahdoost** [comment] 2018-07-30 07:19
@hotrush I get the same error on Debian 8, with php7.2-fpm and laravel 5.6

**Comment by Razorsheep** [comment] 2018-08-01 11:32
@hotrush I'm getting this too, when I try to enable a custom grant from the AuthServiceProviders boot method. Is there a nice way to check whether the key has been created before I try to enable to grant?

**Comment by hotrush** [comment] 2018-08-02 08:00
@Razorsheep i didn't find any good workaround, when deploying first time you just need to generate keys yourself and set valid access rights...

**Comment by edgareler** [comment] 2018-08-15 11:16
In my case this issue happened on OAuth login tests when building on CircleCI. I fixed this issue and by generating the OAuth key pair.
```yaml
steps:
  - run: openssl genrsa -out storage/oauth-private.key 4096
  - run: openssl rsa -in storage/oauth-private.key -pubout > storage/oauth-public.key
```
I added those steps before PHPUnit step.

**Comment by CJDennis** [comment] 2018-08-21 23:09
@edgareler Running those two commands at the command line worked for me.

**Comment by hmuntean-ro** [comment] 2018-09-20 14:03
> @hemorej you must set the owner of the keys to your web server. On mac this helped me
> 
> `sudo chown _www:_www storage/oauth-*.key`

@MrKriegler thanks for this command, it fixed my problem !

**Comment by bluesuiter** [comment] 2018-12-24 11:14
> If the file is not exist use the following cmd
> 
> ```
> php artisan passport:keys
> ```

Thank You buddy :)

**Comment by nazreen** [comment] 2019-06-19 11:26
my context was that I was running a Gitlab CD pipeline and the laravel app is hosted in an ec2 instance.
because I was using rsync, I had to update the folder permissions recursively to my ec2-user. 

the solution for me was to run `chown apache oauth-public.key`

**Comment by ajaymarathe** [comment] 2019-07-24 17:23
> I think you didn't correctly install `passport`.
> 
> Please run this command:
> 
> ```
> php artisan passport:install
> ```

this helps me lot :P thanks

**Comment by mrhili** [comment] 2019-09-04 02:13
Dont do this line untill you have keys in a specific location for the file

in AuthServiceProvider.php


//Passport::loadKeysFrom('/secret-keys/oauth');

**Comment by shivanibenosoft** [comment] 2019-10-14 09:03
Since 

> I think you didn't correctly install `passport`.
> 
> Please run this command:
> 
> ```
> php artisan passport:install
> ```

Since `/storage/*.key` is in .gitignore so if you pull the project, that might be missing the key, so running install command create new keys for you

**Comment by saad-inamdar-fintech** [comment] 2023-01-03 10:15
For Windows OS. If you have already installed passport, or you are setting up an existing application and then facing this problem then try "php artisan passport:keys"

**Comment by madevanni** [comment] 2024-01-05 04:51
This works for me [https://mazer.dev/en/laravel/troubleshooting/how-solve-laravel-oauth-private-key-does-not-exist-or-is-not-readable-copy/](url)
