### ISSUE TITLE
Array to string conversion in DenyAuthorizationController.php (line 46)

### ISSUE THREAD

**Issue by kelvinhalim13** [laravel/passport#536] opened 2017-10-14 02:08 UTC
Laravel passport, after show me an Authorization Request View, i try to cancel the authorize, however i got an error in

`vendor\laravel\passport\src\Http\Controllers\DenyAuthorizationController.php`

        $authRequest = $this->getAuthRequestFromSession($request);

        $uri = $authRequest->getClient()->getRedirectUri();

        $separator = $authRequest->getGrantTypeId() === 'implicit' ? '#' : '?';

        return $this->response->redirectTo(
            $uri.$separator.'error=access_denied&state='.$request->input('state')
        );

the $uri is in array method which contain my client redirect_uri

can someone help me how to solve this ? edit vendor should not be a suggestion.

**Comment by Jalle19** [comment] 2017-11-22 13:39
I'm also getting this error

**Comment by Jalle19** [comment] 2017-11-22 13:41
Duplicate of https://github.com/laravel/passport/issues/457, fixed in https://github.com/laravel/passport/pull/465. @taylorotwell can you close this?

**Closed** 2017-11-23 04:18 UTC
