### ISSUE TITLE
Status of UUID for client_id

### ISSUE THREAD

**Issue by huntsfromshadow** [laravel/passport#366] opened 2017-05-03 14:49 UTC
I know this has been talked about for a while,
but what is the current status of using UUID for client ID?

**Comment by fenos** [comment] 2017-06-06 19:28
We are all waiting for this.

**Comment by JeanLucEsser** [comment] 2017-07-28 11:50
Indeed we are.

**Comment by donromen** [comment] 2017-11-25 15:52
Maybe @heisian can answer this.

**Comment by cweiske** [comment] 2018-02-08 09:32
Duplicate of #14.

**Comment by heisian** [comment] 2018-02-08 18:57
Sadly I'm in `node` world now since that's what my new occupation uses.. If I have some extra time I'll take a look at my `passport` fork and see what's changed - it's been a while. I wouldn't bank on my fork getting merged in anytime soon, though, unless Taylor sees overwhelming support for it.

**Comment by mosleim** [comment] 2018-04-12 10:52
i'm waiting for this updates.

**Comment by diadal** [comment] 2018-07-28 15:59
I create a simple package for this, it convert client id in all the table to Uuid.
https://github.com/diadal/passport

**Comment by mloberg** [comment] 2018-08-17 23:13
You can use UUIDs by updating the migrations and using model listeners. https://mlo.io/blog/2018/08/17/laravel-passport-uuid/

**Comment by driesvints** [comment] 2018-10-16 11:00
Gonna close this as it's a duplicate of #14

**Closed by driesvints** 2018-10-16 11:00 UTC

**Comment by baig772** [comment] 2018-11-20 11:35
> I create a simple package for this, it convert client id in all the table to Uuid.
> https://github.com/diadal/passport

I am having issues installing this. Will this work with Laravel 5.7 ?

**Comment by Sephster** [comment] 2018-11-21 12:41
Probably better to ask that question in the diadal/passport repo instead.
