### ISSUE TITLE
bug to multi auth and multi model ( database )

### ISSUE THREAD

**Issue by webafra** [laravel/passport#585] opened 2017-12-24 21:11 UTC
hi , have a good time .

i want create Multi auth (that have two part (user And Restaurant admin) )
for this do , create two Guard :

```
'guards' => [

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

        'restapi' => [
            'driver' => 'passport',
            'provider' => 'restaurants',
        ],
    ],

```

after Authentication , i created Token ( pesonal token ) with passport .

now with this token, i can see User data ( For Example user id 1 ) with url :
Route::middleware('auth:api')->get('/user', 'UsersController@userInformation');

but this token worked on the Other guard !!!
Route::middleware('auth:restapi')->get('/restaurant', 'api\RestaurantApi@restaurantInformation');

Creation method User Token :
```
    $user = App\User::first();
    $token = $user->createToken('token')->accessToken;
    return $token;
```

Creation method Restaurant Admin Token :
```
    $restaurant = App\Restaurant::find(1);
    $token = $restaurant->createToken('token')->accessToken;
    return $token;
```

two token work to evry guard !

**Comment by bot101** [comment] 2018-01-26 11:19
I am having a similar issue.
`if(Auth::guard('admins')->check()){
return 'admins';
}
if(Auth::guard('users')->check()){
return 'users';
}` 
always returns `admins` no matter which token is used.

**Comment by m-alinasab** [comment] 2018-01-26 12:27
@bot101 : this is a problem On Laravel Passport ( API Route ) .
Auth method Dos`t work On api route and Passport Bearer ( with Token ) .

**Comment by nicolasflorth** [comment] 2018-06-06 06:37
Did you found a solution on this?
Can you share it, please?

**Comment by odupont** [comment] 2018-06-06 07:21
Waiting for Passport to implement multi auth, I use [passport-multiauth](https://github.com/sfelix-martins/passport-multiauth ) to achieve this.

**Comment by m-alinasab** [comment] 2018-06-06 12:42
@nicolasflorth : my problem is resolved with scope
create rule and permissions table and get all permissions for a user .

after : 
```
for Admin :
Route::middleware(['auth:api','scope:admin'])->group(function () {
    Route::post('/admin/info', 'adminController@adminInfo')->middleware('scope:admin_info,administrator');
});

for User :

Route::middleware(['auth:api','scope:user'])->group(function () {
    Route::post('/users/info', 'usersController@userinfo')->middleware('scope:user_info');
});
```

**Comment by nicolasflorth** [comment] 2018-07-06 13:31
@odupont: Can you please share a project that si implementing it? I have things like /oauth/token that I don't succeed in implementing it. Plus some other things related to authentication that I don't understand. It will be fantastic if you can share how you done it.

**Comment by driesvints** [comment] 2018-10-15 12:09
Duplicate of https://github.com/laravel/passport/issues/161

**Closed by driesvints** 2018-10-15 12:09 UTC

**Comment by sumatoreo** [comment] 2020-06-03 17:09
My solution
https://packagist.org/packages/sumatoreo/multi-passport

**Comment by it-one-mm** [comment] 2020-07-09 06:46
> @nicolasflorth : my problem is resolved with scope
> create rule and permissions table and get all permissions for a user .
> 
> after :
> 
> ```
> for Admin :
> Route::middleware(['auth:api','scope:admin'])->group(function () {
>     Route::post('/admin/info', 'adminController@adminInfo')->middleware('scope:admin_info,administrator');
> });
> 
> for User :
> 
> Route::middleware(['auth:api','scope:user'])->group(function () {
>     Route::post('/users/info', 'usersController@userinfo')->middleware('scope:user_info');
> });
> ```

can you share the example project implementing it?
