### ISSUE TITLE
Overriding 'oauth_refresh_tokens' model

### ISSUE THREAD

**Issue by clalos** [laravel/passport#935] opened 2019-01-17 08:57 UTC
Hi there,
I would like to use a different table name for the `oauth_refresh_tokens` table. We can already assign custom models for the other tables inside the `PassportServiceProvider`. Why we can't do the same for that table? What's the easiest way?
This seems a very old issue (#272)

Hardcoded here for example: https://github.com/laravel/passport/blob/d5362c2a709a9d586f4cee576ce60b8b1a1cc514/src/Bridge/RefreshTokenRepository.php#L53

**Comment by driesvints** [comment] 2019-01-17 11:59
Heya, this seems to be a duplicate of https://github.com/laravel/passport/issues/864

**Closed by driesvints** 2019-01-17 11:59 UTC
