### ISSUE TITLE
[proposal] - Support for multiple guards and auth models

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/passport#640] opened 2018-02-16 08:46 UTC
Currently passport does not support authentication via multiple `User` models, guards or suer providers.

I would be willing to write a PR  to enable this functionality, although wont do so unless the maintainers are open to the idea before undertaking the work.

**Comment by driesvints** [comment] 2018-10-15 12:09
Duplicate of https://github.com/laravel/passport/issues/161

**Closed by driesvints** 2018-10-15 12:09 UTC
